#!/bin/bash


system_platform=$(uname)
distribution_name=$(lsb_release -is)
release_version=$(lsb_release -rs)

# if the linux distribution is LINUX
if [ "$system_platform" = "Linux" ]
then
	# check whether the distribution is Ubuntu
	if [ "$distribution_name" = "Ubuntu" ]
	then
		# Install git
		sudo apt-get install -y git cmake

		# Install packages for librealsense
		sudo apt-get install -y libusb-1.0-0-dev pkg-config

		# Install glfw3
		sudo apt-get install -y libglfw3-dev

		# Clone librealsense from github
		git clone https://github.com/IntelRealSense/librealsense.git

		# Install librealsense
		cd librealsense
		mkdir build && cd build
		cmake ..
		make && sudo make install

		# Remove librealsense folder
		cd ../../
		rm -rf librealsense

		# make sure everything work
		sudo ldconfig
	fi
elif [ "$system_platform" = "Darwin" ]
then
	echo "OSX"
else
	echo "Window"
fi
